//! PDF をゼロから作成する例。
//!
//! 実行: `cargo run --example create_pdf`
//! カレントディレクトリに `hello.pdf` を出力する。

use pdf_rust::{Document, DrawOptions, Result, StandardFont, TextOptions};

fn main() -> Result<()> {
    let mut doc = Document::new();

    // A4 ページ（595 x 842 pt）を追加
    doc.add_page(595.0, 842.0)?;

    // 見出し
    doc.add_text(
        0,
        "Hello, PDF from Rust!",
        &TextOptions {
            font: StandardFont::HelveticaBold,
            size: 28.0,
            x: 72.0,
            y: 760.0,
            color: (0.1, 0.1, 0.5),
            ..Default::default()
        },
    )?;

    // 本文（複数行）
    doc.add_text(
        0,
        "This document was generated by pdf_rust,\n\
         a from-scratch PDF library with zero dependencies.\n\
         It supports text, shapes, and metadata.",
        &TextOptions {
            size: 12.0,
            x: 72.0,
            y: 710.0,
            ..Default::default()
        },
    )?;

    // 図形: 枠と下線
    doc.draw_rect(
        0,
        60.0,
        640.0,
        470.0,
        150.0,
        &DrawOptions {
            stroke_color: (0.3, 0.3, 0.3),
            line_width: 1.5,
            ..Default::default()
        },
    )?;
    doc.draw_line(
        0,
        (72.0, 745.0),
        (520.0, 745.0),
        &DrawOptions {
            stroke_color: (0.1, 0.1, 0.5),
            line_width: 2.0,
            ..Default::default()
        },
    )?;

    // 塗り潰し矩形
    doc.draw_rect(
        0,
        72.0,
        560.0,
        120.0,
        40.0,
        &DrawOptions {
            stroke_color: (0.8, 0.4, 0.0),
            fill_color: Some((1.0, 0.85, 0.6)),
            line_width: 1.0,
        },
    )?;

    // 文書情報
    doc.set_title("pdf_rust sample")?;
    doc.set_info_text("Author", "pdf_rust example")?;
    doc.set_info_text("Creator", "create_pdf.rs")?;

    doc.save("hello.pdf")?;
    println!("hello.pdf を出力しました（{} ページ）", doc.page_count());
    Ok(())
}
